-- SmartScan AI: Supabase Database Schema
-- Copy and paste this script into the Supabase SQL Editor to create tables.

-- 1. Products Table
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    stock DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    sku TEXT NOT NULL,
    color TEXT NOT NULL,
    icon TEXT NOT NULL,
    coco_class TEXT
);

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_id TEXT UNIQUE NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL,
    tax DOUBLE PRECISION NOT NULL,
    total DOUBLE PRECISION NOT NULL
);

-- 3. Transaction Items Table
CREATE TABLE IF NOT EXISTS transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL,
    name TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    cost_price DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    qty INTEGER NOT NULL,
    unit TEXT NOT NULL
);

-- Optional: Enable public access policies if needed
-- By default, you can disable Row Level Security (RLS) or add SELECT/INSERT/UPDATE permissions.
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to products" ON products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transactions" ON transactions FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access to transaction_items" ON transaction_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
